pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = 'dockerhub_cred'
        DOCKER_HUB_REPO_FRONTEND = 'sragzhran/frontend_depi_project'
        DOCKER_HUB_REPO_BACKEND = 'sragzhran/backend_depi_project'
        IMAGE_TAG = "V${env.BUILD_NUMBER}"
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')  // Ensure 'aws-access-key-id' matches the credentials ID in Jenkins
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')  // Ensure 'aws-secret-access-key' matches the credentials ID in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: 'github-cred', 
                        url: 'https://github.com/SragZhran73/DEPI-DevOps-FP-G3.git'
                    ]]
                )
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform') {  // Navigate to the directory containing the main.tf file
                    script {
                        sh '''
                        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
                        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
                        terraform init
                        terraform apply -auto-approve
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            build job: 'CD_pipeline', wait: false
            echo 'Successfully triggered CD_pipeline pipeline'
            
            slackSend(
                channel: "depi_g3",
                color: "good",
                message: """
                ${env.JOB_NAME}
                Your Infrastructure is successfully deployed
                """
            )
        }
        failure {
            slackSend(
                channel: "depi_g3",
                color: "danger",
                message: """
                ${env.JOB_NAME}
                Your Infrastructure failed to deploy
                """
            )
        }
    }

}
